# Generated by Django 5.2.15 on 2026-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('primary_doctor', models.CharField(max_length=100)),
                ('current_medications', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('allergies', models.TextField()),
            ],
        ),
    ]
